services:
  go-monitor:
    build: .
    command: ["./app", "--file", "servers.json", "--timeout", "3"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - go-monitor
